<?php
namespace ResourceCatalog\Model;

interface IUserGroup extends IUserGroupIdentify
{
    const ID = array(
        'NULL' => 0,
        'SFGW' => 1,
        'SJWJW' => 2,
        'SWZZB' => 3,
        'SWXCB' => 4,
        'SWZFW' => 5,
        'SWWXB' => 6,
        'SWBB' => 7,
        'SZJRMFY' => 8,
        'SJCY' => 9,
        'SJYJ' => 10,
        'SKJJ' => 11,
        'SGXJ' => 12,
        'SGAJ' => 13,
        'SMZJ' => 14,
        'SSFJ' => 15,
        'SCZJ' => 16,
        'SRSJ' => 17,
        'SGHHZRZRJ' => 18,
        'SHJSTJ' => 19,
        'SZJJ' => 20,
        'SCSGLJ' => 21,
        'SJTYSJ' => 22,
        'SSLJ' => 23,
        'RHLLZH' => 24,
        'SNYNCJ' => 25,
        'SSANGWJ' => 26,
        'SWLJ' => 27,
        'SWJW' => 28,
        'STYJRSWJ' => 29,
        'SSJJ' => 30,
        'SSCJDGLJ' => 31,
        'STYJ' => 32,
        'STJJ' => 33,
        'SYLBZJ' => 34,
        'SXZSPJ' => 35,
        'SJRB' => 36,
        'SYBJFJ' => 37,
        'SNYJ' => 38,
        'SRFB' => 39,
        'SDSJYYJ' => 40,
        'SSWJ' => 41,
        'SFPB' => 42,
        'SJJZD' => 43,
        'SYJJ' => 44,
        'SGGZYJYZX' => 45,
        'SFGJ' => 46,
        'SGJJZX' => 47,
        'SYZJ' => 48,
        'SYCZMJ' => 49,
        'SQXJ' => 50,
        'LLGLFJ' => 51,
        'SCL' => 52,
        'SZGH' => 53,
        'SFL' => 54,
        'SJMYJY' => 55,
        'SXFZD' => 56,
    );
}
