<?php
namespace ResourceCatalog\Model;

interface IUserGroupIdentify
{
    const IDENTIFY = array(
        IUserGroup::ID['NULL'] => 'NULL',
        IUserGroup::ID['SFGW'] => 'SFGW',
        IUserGroup::ID['SJWJW'] => 'SJWJW',
        IUserGroup::ID['SWZZB'] => 'SWZZB',
        IUserGroup::ID['SWXCB'] => 'SWXCB',
        IUserGroup::ID['SWZFW'] => 'SWZFW',
        IUserGroup::ID['SWWXB'] => 'SWWXB',
        IUserGroup::ID['SWBB'] => 'SWBB',
        IUserGroup::ID['SZJRMFY'] => 'SZJRMFY',
        IUserGroup::ID['SJCY'] => 'SJCY',
        IUserGroup::ID['SJYJ'] => 'SJYJ',
        IUserGroup::ID['SKJJ'] => 'SKJJ',
        IUserGroup::ID['SGXJ'] => 'SGXJ',
        IUserGroup::ID['SGAJ'] => 'SGAJ',
        IUserGroup::ID['XMZJ'] => 'XMZJ',
        IUserGroup::ID['SSFJ'] => 'SSFJ',
        IUserGroup::ID['SCZJ'] => 'SCZJ',
        IUserGroup::ID['SRSJ'] => 'SRSJ',
        IUserGroup::ID['SGHHZRZRJ'] => 'SGHHZRZRJ',
        IUserGroup::ID['SHJSTJ'] => 'SHJSTJ',
        IUserGroup::ID['SZJJ'] => 'SZJJ',
        IUserGroup::ID['SCSGLJ'] => 'SCSGLJ',
        IUserGroup::ID['SJTYSJ'] => 'SJTYSJ',
        IUserGroup::ID['SSLJ'] => 'SSLJ',
        IUserGroup::ID['RHLLZH'] => 'RHLLZH',
        IUserGroup::ID['SNYNCJ'] => 'SNYNCJ',
        IUserGroup::ID['SSANGWJ'] => 'SSANGWJ',
        IUserGroup::ID['SWLJ'] => 'SWLJ',
        IUserGroup::ID['SWJW'] => 'SWJW',
        IUserGroup::ID['STYJRSWJ'] => 'STYJRSWJ',
        IUserGroup::ID['SSJJ'] => 'SSJJ',
        IUserGroup::ID['SSCJDGLJ'] => 'SSCJDGLJ',
        IUserGroup::ID['STYJ'] => 'STYJ',
        IUserGroup::ID['STJJ'] => 'STJJ',
        IUserGroup::ID['SYLBZJ'] => 'SYLBZJ',
        IUserGroup::ID['SXZSPJ'] => 'SXZSPJ',
        IUserGroup::ID['SJRB'] => 'SJRB',
        IUserGroup::ID['SYBJFJ'] => 'SYBJFJ',
        IUserGroup::ID['SNYJ'] => 'SNYJ',
        IUserGroup::ID['SRFB'] => 'SRFB',
        IUserGroup::ID['SDSJYYJ'] => 'SDSJYYJ',
        IUserGroup::ID['SSWJ'] => 'SSWJ',
        IUserGroup::ID['SFPB'] => 'SFPB',
        IUserGroup::ID['SJJZD'] => 'SJJZD',
        IUserGroup::ID['SYJJ'] => 'SYJJ',
        IUserGroup::ID['SGGZYJYZX'] => 'SGGZYJYZX',
        IUserGroup::ID['SFGJ'] => 'SFGJ',
        IUserGroup::ID['SGJJZX'] => 'SGJJZX',
        IUserGroup::ID['SYZJ'] => 'SYZJ',
        IUserGroup::ID['SYCZMJ'] => 'SYCZMJ',
        IUserGroup::ID['SQXJ'] => 'SQXJ',
        IUserGroup::ID['LLGLFJ'] => 'LLGLFJ',
        IUserGroup::ID['SCL'] => 'SCL',
        IUserGroup::ID['SZGH'] => 'SZGH',
        IUserGroup::ID['SFL'] => 'SFL',
        IUserGroup::ID['SJMYJY'] => 'SJMYJY',
        IUserGroup::ID['SXFZD'] => 'SXFZD',
    );
}
